Plugins can declare build function in order to perform arbitrary work during installation.

diff --git a/bin/libnapalm b/bin/libnapalm
--- a/bin/libnapalm
+++ b/bin/libnapalm
@@ -254,8 +254,8 @@ extract_program() {
 # example:
 # install_program foo 1.3
 install_program() {
-  [[ -z "$1" ]] && return 4
-  [[ -z "$2" ]] && return 5
+  [[ -z "$1" ]] && return 5
+  [[ -z "$2" ]] && return 6
 
   VERSION="$2"
   load_plugin "$1" || {
@@ -283,6 +283,14 @@ install_program() {
 
   mv "extracted/$program" "$NAPALM_PROGRAMS_DIR/$1-$VERSION"
   ln -s "$NAPALM_PROGRAMS_DIR/$1-$VERSION" "$NAPALM_PROGRAMS_DIR/$1"
+
+  if hash build 2> /dev/null; then
+    cd "$NAPALM_PROGRAMS_DIR/$1-$VERSION"
+    build || {
+      echo "Failed to build $1-$VERSION" 1>&2
+      return 4
+    }
+  fi
 
   local program_rc="$NAPALM_USER_HOME/${1}.sh"
   if [[ ! -f "$program_rc" && -n "$PROGRAM_ENV" ]]; then
